require("mason").setup()
require("mason-lspconfig").setup()
-- local mason_lspconfig = require("mason-lspconfig")
-- local lspconfig = require("lspconfig")
--
-- -- Extension to bridge mason.nvim with the lspconfig plugin
-- mason_lspconfig.setup(
--   {
--     ensure_installed = {
--       "json-lsp",
--       "lua-language-server",
--       "pyright",
--       "typescript-language-server",
--       "solargraph",
--       "gopls",
--       "vim-language-server",
--       "yaml-language-server",
--       "golangci-lint-langserver",
--       "powershell-editor-services",
--       "puppet-editor-services",
--       "markdownlint",
--       "yamllint"
--     },
--     install_automatically = true,
--   }
-- )
--
-- local opts = {
--   on_attach = lspconfig.on_attach,
--   capabilities = lspconfig.capabilities,
-- }
--
-- mason_lspconfig.setup_handlers({
--   function(server_name)
--     lspconfig[server_name].setup {
--       on_attach = opts.on_attach,
--       capabilities = opts.capabilities,
--     }
--   end
-- })
